### ISSUE TITLE
Let different parts of the clip be set to fastmo and other parts to slowmo or regmo

### ISSUE THREAD

**Issue by samyost** [dkuc/shadowclip#7]
Let different parts of the clip be set to fastmo and other parts to slowmo or regmo. Basically give a way to fastforward between boring parts of the round.

**Comment by dkuc** [comment]
I like it. Lot of work -   I'll have to discuss this with all the stakeholders.

**Comment by samyost** [comment]
I am the stakeholder. Literally unplayable.

**Comment by dkuc** [comment]
Done.
https://github.com/dkuc/shadowclip/commit/57f5c457fc725916d47ad7aa5d09fa5055d57051
